### PR TITLE
Add highlighting of known_hosts files

### PR DESCRIPTION
**Pull request by walles**
Here's what it looks like with the Atom Light syntax theme:
highlighted-known-hosts

I get to edit those from time to time and getting this highlighting in here would make that experience just a little bit better :).

### CODE REVIEW

**Comment by walles** [comment]
@lalyos would you like me to squash my changes into one?

**Comment by walles** [comment]
Thanks for merging @lalyos!

Releasing is pretty easy, so if you could make a release right now with only this change added that would be awesome!

Then, if the other PR gets some unit tests, just make another one after merging that.

To paraphrase Mr. Balmer: "Delivery, delivery, delivery!" :) /J

**Comment by walles** [comment]
@lalyos Could you please `apm publish minor`?

I'd love to be able to use my changes!

**Comment by walles** [comment]
@lalyos, could you please make a new release now that this change has been merged?

**Comment by lalyos** [comment]
done:

```
Preparing and tagging a new version ✓
Pushing v0.12.0 tag ✓
Publishing ssh-config@v0.12.0 ✓
```

Sorry, it took me soo long, but im on vacation, and moved to a new laptop, and lost all kinds of tokens/access ...

**Comment by walles** [comment]
Thanks for releasing @lalyos, just tested it and your new release works like a charm :).

**Pull request merged**
