### PR TITLE
Add macOS Keychain properties to grammar

### PR DESCRIPTION
**Pull request by caleb531**
When Apple released macOS Sierra, the `ssh-add` utility would no longer automatically save user's SSH passphrases to their keychain. This behavior could be re-enabled via two `ssh_config` properties: `AddKeysToAgent` and `UseKeychain`

Here's a reference to where these properties are mentioned: https://github.com/jirsbek/SSH-keys-in-macOS-Sierra-keychain#readme

**Before:**  
before

**After:**  
after

While these properties are technically proprietary, I still think they ought to be syntax-highlighted because they have practical value to any macOS dev.

### CODE REVIEW

**Comment by lalyos** [comment]
@caleb531 its conflicting now. Please rebase.

**Comment by caleb531** [comment]
@lalyos Okay, I've rebased to fix the conflicts! This branch can now be cleanly merged.

**Comment by lalyos** [comment]
thanks!

**Comment by lalyos** [comment]
I just release 0.13.0 including the 2 latest PR

**Pull request merged**
